name: CI/CD - Strapi Deployment

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: strapi-appmaxxy
  AWS_ACCOUNT_ID: 607700977843
  CONTAINER_NAME: madhan-strapi
  ECS_CLUSTER: madhan-strapi-cluster
  ECS_SERVICE: madhan-strapi-service
  CODEDEPLOY_APP_NAME: madhan-strapi
  CODEDEPLOY_DEPLOYMENT_GROUP: madhan-strapi-dg

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate image tag
        id: tag
        run: |
          echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
          echo "${IMAGE_TAG}" > image_tag.txt

      - name: Build, tag, and push image to ECR
        run: |
          docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Upload image tag artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tag
          path: image_tag.txt

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply with image tag
        run: |
          terraform apply -auto-approve \
            -var="image_tag=${IMAGE_TAG}" \
            -var="ecr_repo=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}"

      - name: Trigger CodeDeploy deployment
        id: deploy
        run: |
          deployment_id=$(aws deploy create-deployment \
            --application-name $CODEDEPLOY_APP_NAME \
            --deployment-group-name $CODEDEPLOY_DEPLOYMENT_GROUP \
            --revision revisionType=AppSpecContent,appSpecContent="{\"content\":\"version: 0.0\nResources:\n  - TargetService:\n      Type: AWS::ECS::Service\n      Properties:\n        TaskDefinition: arn:aws:ecs:${AWS_REGION}:${AWS_ACCOUNT_ID}:task-definition/madhan-strapi-task\"}" \
            --query "deploymentId" --output text)
          echo "Deployment triggered: $deployment_id"
          echo "deployment_id=$deployment_id" >> $GITHUB_ENV
          echo "::set-output name=deployment_id::$deployment_id"

      - name: Wait for deployment to complete
        run: |
          echo "Waiting for deployment $DEPLOYMENT_ID to finish..."
          aws deploy wait deployment-successful --deployment-id "$DEPLOYMENT_ID"

      - name: Confirm deployment success
        run: echo "Deployment $DEPLOYMENT_ID completed successfully."

      - name: Rollback if deployment fails
        if: failure()
        run: |
          DEPLOYMENT_ID=${{ steps.deploy.outputs.deployment_id }}
          echo "Deployment failed. Checking status..."
          aws deploy get-deployment --deployment-id "$DEPLOYMENT_ID"
          echo "Rolling back..."
          aws deploy stop-deployment --deployment-id "$DEPLOYMENT_ID" --auto-rollback-enabled


