name: CI - Strapi

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-2
  IMAGE_NAME: strapi-appmaxxy

jobs:
  build-and-push:
    name: Build & Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set IMAGE_URI
        run: |
          echo "IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_ENV

      - name: Build Docker Image with tag `latest`
        run: |
          docker build -t $IMAGE_URI ./my-strapi

      - name: Push Docker Image to ECR
        run: |
          docker push $IMAGE_URI

      - name: Output Image URI
        run: |
          echo "Image pushed to: $IMAGE_URI"
